### ISSUE TITLE
Ajustes do Spring

### ISSUE THREAD

**Issue by boaglio** [rodrigorodrigues/rinha-de-backend-2024-q1-javaslow-spring#2]
Olá @rodrigorodrigues , dei uma olhada rápida no seu projeto, e a minha sugestão baseada na minha experiência com a primeira rinha de back-end é retirar o actuator (como vc usa no compose para checar o health, vc pode criar um end-point para isso) e o spring validation (esse vai gerar um monte de IF horrível no código kkk).

Nos testes que fiz (era Spring Boot 3.1.3) deu uma boa diferença quando tirei esses 2... sugiro que você faça um teste!

**Comment by rodrigorodrigues** [comment]
Valeu @boaglio depois vou tentar fazer esse teste mas sem bean validation fica estranho mesmo o codigo eu vi o seu exemplo. O Actuator nao deveria afetar performance creio ele eh soh chamado pra verificar no docker-compose pra saber quando o service esta up.

**Comment by rodrigorodrigues** [comment]
Fala @boaglio, acabei seguindo a sua sugestão e tirei spring validation e actuator do class path valeu!
